# SMPAR-GUI-Version
FROM raspbian/stretch
MAINTAINER Eliott Foust (wefoust@ucar.edu)
SHELL ["/bin/bash","-c"]
ENV     DIR=/pi-wrf/WRF_System/lib/LIBRARIES                       \
        CC=gcc                                                     \
        FC=gfortran                                                \
        F77=gfortran                                               \
        CXX=g++                                                    \
        JASPERLIB=/pi-wrf/WRF_System/lib/LIBRARIES/grib2/lib       \
        JASPERINC=/pi-wrf/WRF_System/lib/LIBRARIES/grib2/include   \
        NETCDF=/pi-wrf/WRF_System/lib/LIBRARIES/netcdf             \
        NCARG_ROOT=/pi-wrf/WRF_System/ncl_6.4.0                    \
	WRFIO_NCD_LARGE_FILE_SUPPORT=1                             \
	PATH="${NCARG_ROOT}/bin:${PATH}"


ENV PATH="${NCARG_ROOT}/bin:${PATH}"
ENV PATH="/pi-wrf/WRF_System/lib/LIBRARIES/netcdf/bin:${PATH}"
ENV PATH="/pi-wrf/WRF_System/lib/LIBRARIES/mpich/bin:${PATH}"


        ####### DOWNLOADING LIBRARIES ######################
RUN apt-get update && apt-get install -y \
        wget                         \
        csh                          \
        nco                          \
        m4                           \
        libpng-dev                   \
        gfortran                     \
        file                         \
        make                         \
        curl                         \
        g++                          \
        build-essential              \
	libpng12-0                   \
	python3-pip                  \
	imagemagick                  \
	unzip                        \
        python3-pil.imagetk          \
        python3-matplotlib           \
        python3-mpltoolkits.basemap  \
	&& apt-get autoremove -y     \
        && apt-get clean -y          \
	&& pip3 install requests     \
	#
        #
        ########     SETTING UP DIRECTORIES                  #############################
        && mkdir -p /pi-wrf/WRF_System/lib/LIBRARIES         \
        && mkdir /pi-wrf/WRF_System/lib/DATA/                \
        && mkdir -p /pi-wrf/pi_wrf/pi_wrf                    \
	&& mkdir -p /pi-wrf/pi_wrf/pi_wrf/Pages              \
	&& mkdir -p /pi-wrf/Output/user_saved_files          \
        && mkdir -p /pi-wrf/WRF_System/Plotting_Scripts      \
        #
        #
        ############   SETTING UP ALIASES     ###############
        && echo "alias run='python3 /pi-wrf/pi_wrf/pi_wrf/Runner.py'" >> ~/.bashrc   \
        && source ~/.bashrc                                                          \
        #
        #
        #########   DOWNLOADING AND INSTALLING DEPENDENCIES     ##########################
	#
        #
	# DOWNLOADING AND INSTALLING WRF
	&& cd /pi-wrf/WRF_System/                                                  \
	&& curl -O -L -J -k http://www2.mmm.ucar.edu/wrf/src/WRFV3.9.1.TAR.gz      \
	&& tar -zxvf /pi-wrf/WRF_System/WRFV3.9.1.TAR.gz -C /pi-wrf/WRF_System/    \
	&& rm /pi-wrf/WRF_System/*.gz                                              \
	#
	#
	# DOWNLOADING AND INSTALLING WPS
	&& curl -O -L -J -k https://github.com/wrf-model/WPS/archive/v4.1.tar.gz          \
	&& tar -zxvf /pi-wrf/WRF_System/WPS-4.1.tar.gz -C /pi-wrf/WRF_System/             \
	&& mv WPS-4.1 WPS                                                                 \
	&& rm *.gz                                                                        \
	#
	#
	# DOWNLOADING AND INSTALLING NCL 6.4.0 LIBRARY
        && wget --no-check-certificate https://www2.cisl.ucar.edu/sites/default/files/ncl_6.4.0.tar_.zip     \
        && unzip ncl_6.4.0.tar_.zip -d /pi-wrf/WRF_System/                                                   \
        && rm *.zip                                                                                          \
        && tar -xvf ncl_6.4.0.tar                                                                            \
	&& rm *.tar                                                                                          \
        #
        #
        # INSTALLING NETCDF LIBRARY
	&& cd $DIR/                                                                                                     \
        && curl -O -L -J -k http://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/netcdf-4.1.3.tar.gz  \
                --output $DIR/netcdf-4.1.3.tar.gz                                                                       \
        && tar -zxvf $DIR/netcdf-4.1.3.tar.gz  -C $DIR/                        						\
	&& cd $DIR/netcdf-4.1.3                                                                 			\
        && ./configure --prefix=$DIR/netcdf --disable-dap --disable-netcdf-4 --disable-shared   			\
        && make                                                                                 			\
        && make install                                                                         			\
        #
        #
        #  INSTALLING MPICH LIBRARY
        && cd $DIR/												           \
	&& curl -O -L -J -k http://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/mpich-3.0.4.tar.gz      \
	            --output $DIR/mpich-3.0.4.tar.gz                                                                       \
        && tar -zxvf $DIR/mpich-3.0.4.tar.gz -C $DIR/                         						   \
	&& cd $DIR/mpich-3.0.4/                     						                           \
        && ./configure --prefix=$DIR/mpich            									   \
        && make                                       									   \
        && make install                  								                   \
        #
        #
        # Installing ZLIB LIBRARY                     
        && cd $DIR/ 													  \
	&& curl -O -L -J -k http://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/zlib-1.2.7.tar.gz      \
	            --output $DIR/zlib-1.2.7.tar.gz                                                                       \
        && tar -zxvf $DIR/zlib-1.2.7.tar.gz -C $DIR/                      						  \
	&& cd $DIR/zlib-1.2.7/                        									  \
        && ./configure --prefix=$DIR/grib2            									  \
        && make                                       									  \
        && make install                             									  \
        #
        #
        # INSTALLING LIBPNG LIBRARY
        && cd $DIR/													\
	&& curl -O -L -J -k http://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/libpng-1.2.50.tar.gz \
	            --output $DIR/libpng-1.2.50.tar.gz                                                                  \
	&& tar -zxvf $DIR/libpng-1.2.50.tar.gz -C $DIR/                        						\
	&& cd $DIR/libpng-1.2.50/                     									\
        && ./configure --prefix=$DIR/grib2            									\
        && make                                       									\
        && make install                               	 							        \
        #
        #
        # INSTALLING JASPER LIBRARY
        && cd $DIR/ 													  \
	&& curl -O -L -J -k http://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/jasper-1.900.1.tar.gz  \
	            --output $DIR/jasper-1.900.1.tar.gz                                                                   \
	&& tar -zxvf $DIR/jasper-1.900.1.tar.gz -C $DIR/                                                                  \
	&& cd $DIR/jasper-1.900.1/                    									  \
        && ./configure --prefix=$DIR/grib2            									  \
        && make                                       									  \
        && make install                               									  \
	&& rm $DIR/*.gz                                                      						  \
        #
        #
	# DOWNLOADING STATIC DATA for WPS 4.1
	&& cd /pi-wrf/WRF_System/lib/                                                                               \
	&& wget --no-check-certificate http://www2.mmm.ucar.edu/wrf/src/wps_files/geog_low_res_mandatory.tar.gz     \
	&& tar xvf geog_low_res_mandatory.tar.gz                                                                    \
	&& mv WPS_GEOG_LOW_RES WPS_GEOG                                                                             \
	&& rm *.gz                                                                                                  \
	#
        # CONFIGURING  AND Compile WRFV3.9.1-DMPAR
        # To compile a serial implementation use option 32, SMPAR option 33, DMPAR option 34
        && cd /pi-wrf/WRF_System/WRFV3/                                                                                \
        && grep -rl x86_64 /pi-wrf/WRF_System/WRFV3/arch/configure_new.defaults | xargs sed -i 's/x86_64/armv7l/g'     \
        && cd /pi-wrf/WRF_System/WRFV3/                                                                                \
        && ./configure <<< $'33\r1\r'                                                                                  \
        && ./compile em_real >& log.compile                                                                            \
        #
        #
        #CONFIGURE & COMPILE WPS 4.1
        && sed -i 's/FFFFFFFF00000000/FFFFFFFF0000000/g' /pi-wrf/WRF_System/WPS/ungrib/src/ngl/g2/intmath.f                           \
        && grep -rl x86_64 /pi-wrf/WRF_System/WPS/arch/configure.defaults | xargs sed -i 's/x86_64/armv7l/g'                          \
        && cd /pi-wrf/WRF_System/WPS/                                                                                                 \
        && sed -i 's/CONFIGURE_NETCDFF_LIB -lnetcdf/CONFIGURE_NETCDFF_LIB -lnetcdf -lgomp/g' /pi-wrf/WRF_System/WPS/arch/preamble     \
        && ./configure <<< $'1\r1\r'                                                                                                  \
        && ./compile


ADD /resources/images/* /pi-wrf/WRF_System/lib/
ADD /resources/*.csv /pi-wrf/WRF_System/lib/
ADD /resources/ref_namelist.wps /pi-wrf/WRF_System/WPS/namelist.wps
ADD /resources/ref_namelist.input /pi-wrf/WRF_System/WRFV3/run/namelist.input
ADD /src/cleanwrf /pi-wrf/WRF_System/lib/
ADD /src/Plotting_Scripts/* /pi-wrf/WRF_System/lib/Plotting_Scripts/
ADD /src/pi-wrf/*.*  /pi-wrf/pi_wrf/pi_wrf/
ADD /src/pi-wrf/Pages/* /pi-wrf/pi_wrf/pi_wrf/Pages/
ADD /src/run_wrf /pi-wrf/


WORKDIR /pi-wrf/pi_wrf/pi_wrf
CMD python3 /pi-wrf/pi_wrf/pi_wrf/Runner.py 
