#!/bin/bash
#Setting Paths
export wrf_basis=$(readlink -f $(dirname $(basename $0)))
export wrf_basis=$(cd $wrf_basis/../../ && pwd)
export wrf_path=$wrf_basis/WRF_System
export wrf_output=$wrf_basis/Output
export NCARG_ROOT=$wrf_path/ncl_6.4.0
export PATH=$NCARG_ROOT/bin:$PATH
export WRFIO_NCD_LARGE_FILE_SUPPORT=1


source_file='addfile("'$wrf_basis'/Output/Temp_WRF_Output","r")'
city_names='asciiread("'$wrf_path'/lib/World-City-Pop.csv",-1,"string")'
output=('gsn_open_wks("png","'$wrf_basis'/Output/High_Temperature")'
	'gsn_open_wks("png","'$wrf_basis'/Output/Low_Temperature")'
        'gsn_open_wks("png","'$wrf_basis'/Output/Total_Precip")'
        'gsn_open_wks("png","'$wrf_basis'/Output/Snow_Depth")'
        'gsn_open_wks("png","'$wrf_basis'/Output/Your_Domain")'
        'gsn_open_wks("png","'$wrf_basis'/Output/Your_Domain_Relative")')

#Run Plotting Scripts
echo Plotting High Temperature for your forecast period
sed -i "/gsn_open_wks/c\wks=${output[0]}" $wrf_path/lib/Plotting_Scripts/Dynamic_High_Temperature
ncl a=$source_file csv_file=$city_names $wrf_path/lib/Plotting_Scripts/Dynamic_High_Temperature 



echo Plotting Low Temperature for your forecast period
sed -i "/gsn_open_wks/c\wks=${output[1]}" $wrf_path/lib/Plotting_Scripts/Dynamic_Low_Temperature
ncl  a=$source_file csv_file=$city_names $wrf_path/lib/Plotting_Scripts/Dynamic_Low_Temperature &>/dev/null 



echo Plotting accumulated rainfall
sed -i "/gsn_open_wks/c\wks=${output[2]}" $wrf_path/lib/Plotting_Scripts/Dynamic_Precip
ncl -Q a=$source_file csv_file=$city_names $wrf_path/lib/Plotting_Scripts/Dynamic_Precip &>/dev/null
echo

echo Plotting snow accumulation
sed -i "/gsn_open_wks/c\wks=${output[3]}" $wrf_path/lib/Plotting_Scripts/Dynamic_Snow
ncl -Q a=$source_file csv_file=$city_names $wrf_path/lib/Plotting_Scripts/Dynamic_Snow &>/dev/null
echo

echo Plotting Reference Maps
sed -i "/gsn_open_wks/c\wks=${output[4]}" $wrf_path/lib/Plotting_Scripts/Plot_Domain
ncl -Q a=$source_file csv_file=$city_names $wrf_path/lib/Plotting_Scripts/Plot_Domain &>/dev/null

sed -i "/gsn_open_wks/c\wks=${output[5]}" $wrf_path/lib/Plotting_Scripts/Plot_Domain_Relative
ncl -Q a=$source_file csv_file=$city_names $wrf_path/lib/Plotting_Scripts/Plot_Domain_Relative &>/dev/null